# Workflow 이름
name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정
# main 브랜치에 push 될 때 아래 Workflow 실행
on:
  push:
    branches:
      main

# 하나의 Workflow는 1개 이상의 Job으로 구성
# Job는 기본적으로 병렬적으로 수행
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # Github Actions를 실행시킬 서버 종류 선택
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성
    steps:
      - name: Hello World 찍기 # Step 이름 설정
        run: echo "Hello World" # 실행시킬 명령어 작성

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"

      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}